### PR TITLE
Convert test to Typescript and improve code quality

### PR DESCRIPTION
**Pull request by ansidev**

### CODE REVIEW

**Comment by ansidev** [comment]
@dalenguyen In the latest commit of this PR, I changed the way to pass the service account key for testing purpose.
For Travis CI, you just need to set environment variables from Travis CI Dashboard.

**Comment by dalenguyen** [comment]
Thanks @ansidev, I will check it over the weekend.

**Comment by ansidev** [comment]
@dalenguyen The CI is still failing. Have you added the environment variables to TravisCI?

**Comment by dalenguyen** [comment]
@ansidev I added the variables to Travis dashboard. Somehow, there is something wrong with the way it parses the private key. I will investigate later.

```
> firebase-functions-helper@0.6.1 test /home/travis/build/dalenguyen/firebase-functions-helper
> mocha --timeout 99999999 --exit -r ts-node/register test/**/*.spec.ts
/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/utils/error.js:39
        var _this = _super.call(this, errorInfo.message) || this;
                           ^
Error: Failed to parse private key: Error: Invalid PEM formatted message.
    at FirebaseAppError.FirebaseError [as constructor] (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at new Certificate (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/auth/credential.js:125:19)
    at new CertCredential (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/auth/credential.js:173:64)
    at Object.cert (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/firebase-admin/lib/firebase-namespace.js:220:58)
    at FirebaseHelper.initializeApp (/home/travis/build/dalenguyen/firebase-functions-helper/src/firebase.ts:13:42)
    at Object.<anonymous> (/home/travis/build/dalenguyen/firebase-functions-helper/test/appInitialize.ts:4:44)
    at Module._compile (module.js:653:30)
    at Module.m._compile (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/dalenguyen/firebase-functions-helper/test/firestore.spec.ts:3:1)
    at Module._compile (module.js:653:30)
    at Module.m._compile (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/travis/build/dalenguyen/firebase-functions-helper/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/travis/build/dalenguyen/firebase-functions-helper/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by ansidev** [comment]
@dalenguyen This error is because `\n` in field private_key will be escaped to `\\n`.

**Comment by dalenguyen** [comment]
@ansidev It should be fixed through "**.replace(/\\n/g, '\n')**"

**Comment by ansidev** [comment]
@dalenguyen Fixed
Passed build https://travis-ci.org/ansidev/firebase-functions-helper/builds/475782146.

1. Please reset to this commit https://github.com/dalenguyen/firebase-functions-helper/commit/b24c3299943b46fb2a550fe492245bc71588aa53.
2. Create file `end.prod.sh` then add all env variables like `env.test.sh`.
3. Execute `travis encrypt-file env.prod.sh --add`
4. Go to `.travis.yml`, add `- source env.prod.sh` after `before_install` > openssl...
5. Add env.prod.sh to .gitignore to make sure it won't be committed.
6. Commit and push following files: `.gitignore`, `.travis.yml`, `env.prod.sh.enc`.

**Comment by ansidev** [comment]
@dalenguyen Because you export env vars from env.prod.sh, so you should remove them from Travis CI Dashboard.

**Comment by dalenguyen** [comment]
@ansidev Yeah. It's fixed. Could be a glitch from Travis.

**Comment by dalenguyen** [comment]
@ansidev Thanks for your contribution. It was a big help!

**Pull request merged**
